In [1]:
import torch
import matplotlib.pyplot as plt 

In [3]:
torch.manual_seed(10)
lr = 0.05

In [4]:
x = torch.rand(20, 1) * 10  # 均匀分布
y = 2*x + (5 + torch.randn(20, 1))

In [5]:
x.shape, y.shape

(torch.Size([20, 1]), torch.Size([20, 1]))

In [6]:
# 初始化参数
w = torch.randn((1), requires_grad=True)
b = torch.zeros((1), requires_grad=True)

In [11]:
wgrad=[]
bgrad=[]
for iteration in range(10):
    # 前向传播
    wx = torch.mul(w, x)
    y_pred = torch.add(wx, b)
    # 计算loss
    loss = (0.5 * (y - y_pred) ** 2).mean()
    # 反向传播
    loss.backward()
    # 更新参数
    w.data.sub_(lr * w.grad)
    b.data.sub_(lr * b.grad)
    print(w.grad,b.grad)
    # 对梯度进行清零
    wgrad.append(w.grad)
    bgrad.append(b.grad)
    w.grad.zero_()
    b.grad.zero_()
    

    if iteration % 20 == 0:
        print(loss)


tensor([0.0045])tensor([-0.3174])
tensor(0.9022, grad_fn=<MeanBackward0>)
tensor([0.0836])tensor([-0.3027])
tensor([0.0253])tensor([-0.3104])
tensor([0.0674])tensor([-0.3018])
tensor([0.0361])tensor([-0.3051])
tensor([0.0585])tensor([-0.2997])
tensor([0.0417])tensor([-0.3007])
tensor([0.0535])tensor([-0.2971])
tensor([0.0444])tensor([-0.2969])
tensor([0.0506])tensor([-0.2941])


In [8]:
wgrad,bgrad

([tensor([0.]),
  tensor([0.]),
  tensor([0.]),
  tensor([0.]),
  tensor([0.]),
  tensor([0.]),
  tensor([0.]),
  tensor([0.]),
  tensor([0.]),
  tensor([0.])],
 [tensor([0.]),
  tensor([0.]),
  tensor([0.]),
  tensor([0.]),
  tensor([0.]),
  tensor([0.]),
  tensor([0.]),
  tensor([0.]),
  tensor([0.]),
  tensor([0.])])